# Site Build Settings

# Pagination configuration
paginate: 8

# Drafts configuration
show_drafts: false

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-redirect-from, jekyll-include-cache]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Laurence Andrews'
# description:	       'MY CORNER OF THE NET'
author:              'Laurence Andrews'

url: "https://andrews.io"

imagesurl: "/assets/img/"
thumbsurl: "/assets/img/"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
