# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- name: 'Lists'
  path: '#'
  dropdown:
    - {name: 'The List', path: 'menu', url: 'thelist.html'}
    - {name: 'Countries', path: 'menu', url: 'countries.html'}
    - {name: 'Table', path: 'menu', url: 'table.html'}
    - {name: 'Stage', path: 'menu', url: 'stage.html'}
    - {name: 'Movies', path: 'menu', url: 'movies.html'}
    - {name: 'Books', path: 'menu', url: 'books.html'}
- name: 'Other'
  path: '#'
  dropdown:
    - {name: 'Photos', path: 'menu', url: 'photos.html'}
    - {name: 'Rail Map', path: 'menu', url: 'railmap.html'}
    - {name: 'Archive', path: 'menu', url: 'archive.html'}

link:
- {name: 'Social', path: 'ext', url: 'https://mastodon.world/@14zz4'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {fa-type: 'fab', icon: 'mastodon', link: 'https://mastodon.world/@14zz4'}
- {fa-type: 'fas', icon: 'envelope', link: 'mailto:laurence@andrews.io'}
- {fa-type: 'fas', icon: 'rss-square', link: '/feed.xml'}

# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Other Posts:'

post_date_prefix: 'Written on'
